### ISSUE TITLE
$input  = new \WxPayUnifiedOrder(); ？？？

### ISSUE THREAD

**Issue by STUDOME** [dream2023/ThinkPHP5-wxpay#5]
wxPay.php文件里面 实例化的WxPayUnifiedOrder这个类，在包文件里面没有找到。请问这个类是文件吗？... 本来想直接调用这个库的,由于要把代码转成ci框架的,没办法,只能边看边学。

$input  = new \WxPayUnifiedOrder(); ？？？

>     // 组装请求参数  wxPay.php
>     private function getPostData($params)
>     {
>         $input  = new \WxPayUnifiedOrder();
>         $input->SetBody($params['body']);
>         $input->SetOut_trade_no($params['out_trade_no']);
>         $input->SetTotal_fee($params['total_fee']);
>         // $input->SetGoods_tag("test");
>         $input->SetNotify_url(\WxPayConfig::NOTIFY_URL);
>         $input->SetTrade_type('MWEB');
>         return $input;
>     }

**Comment by dream2023** [comment]
你用的什么开发工具？

**Comment by STUDOME** [comment]
我目前再用phpstrom再看代码,我单独打开压缩包  压缩包里面也没有这个文件，我没有运行代码试过，不知道代码对不对。

**Comment by STUDOME** [comment]
好了  谢谢哥   在WxPayData 里面找到了~
